### PR TITLE
Name transition matrix processing extension

### PR DESCRIPTION
**Pull request by aXises**
Better hide the functionality of the application along with optimizations to parallel byte comparator and processing

### CODE REVIEW

**Comment by BradF-99** [comment]
@Assasindie please review.

**Comment by BradF-99** [comment]
@Assasindie please review.

**Comment by BradF-99** [comment]
@Assasindie please review.

**Comment by Assasindie** [comment]
SORRY THIS IS AN ANIME CHROME CRASHER NOT A RUNESCAPE CHROME CRASHER

**Comment by aXises** [comment]
yeah so are we play/merge?

**Pull request closed without merging**
